### ISSUE TITLE
DMN Editor Import Java Datatype disabled

### ISSUE THREAD

**Issue by MBoegers** [apache/incubator-kie-tools#1179] opened 2022-08-15 12:58 UTC
I try to use a domain model from a maven dependency within a kjar generated by the archetype.
When I open the kjar project with DMN Editor plugin, navigate to the _Data Types_ Tab, the _Import Java classes_ Button is disabled.
I've created a project to reproduce the problem under [MBoegers/kjar-with-domain-from-dependency](https://github.com/MBoegers/kjar-with-domain-from-dependency)

org.kie.version: 7.73.0.Final

plugin version: v0.21.0

Error from Developer Tools
```
dmn-loader.js:2 Error: Internal error.
    at e.callback (DmnEditorEnvelopeApp.js:2:517269)
    at e.receive (DmnEditorEnvelopeApp.js:2:519025)
    at Object.receive (DmnEditorEnvelopeApp.js:2:514342)
    at e.receive (DmnEditorEnvelopeApp.js:2:521554)
    at eventListener.eventListener (DmnEditorEnvelopeApp.js:2:520714)
(anonymous) @ dmn-loader.js:2
Promise.catch (async)
(anonymous) @ dmn-loader.js:2
Pl @ dmn-loader.js:2
t.unstable_runWithPriority @ dmn-loader.js:2
Yo @ dmn-loader.js:2
Bl @ dmn-loader.js:2
(anonymous) @ dmn-loader.js:2
R @ dmn-loader.js:2
w.port1.onmessage @ dmn-loader.js:2
```

**Comment by yesamer** [comment] 2022-08-22 08:35
Hi @MBoegers!
To enable the `Import Java Classes` button, you can refer to [my blog post in kie blog](https://blog.kie.org/2022/05/dmn-types-from-java-classes.html)
Please keep in mind this feature is designed to work with `kogito` (https://kogito.kie.org/), which is not your case (as you are using the `7.x` kie version. 
Despite the feature wasn't tested with the `7.x` stream, it should work. Pay attention when using the `@KieActivator` annotation. That could require importing `kie-api` dependency in your project.
Let me know if face any issues.

**Comment by MBoegers** [comment] 2022-08-23 08:10
Hi @yesamer the new popup provides better information, thanks for that improvement.

I can not make it work with 7.x nor with 8.x.. 
My process:
1. create project with ´mvn archetype:generate -DarchetypeGroupId=org.kie -DarchetypeArtifactId=kie-kjar-archetype -DarchetypeVersion=8.26.0.Beta´ (for 7.x I used archetype version 7.73.0.Final)
2. add Person class with public getter/setter to ´src/main/java/io/..´
3. add class with Annotation ´org.kie.api.project.KieActivator.KieActivator´ in same package as Person
4. run mvn package
5. add Person.dmn to _src/main/resources_

The Button stays disables, but with the new popup message. I've updated my reproducer, maybe you can see where I've missed something.

VSCode version: 1.70.2, Language Support for Java by Red Hat v1.9.0, Red Hat Business Automation Bundle v0.22..0

**Edit:** with the dmn-quarkus-example it is possible, so it seems to be an issue with my setup..

**Comment by yesamer** [comment] 2022-08-24 07:33
@MBoegers I'm able to reproduce the issue, it's a bug on our side. I'll provide a fix in the same PR.

**Comment by yesamer** [comment] 2022-08-24 08:42
@MBoegers PR updated. That fix would be part of the next `0.23.0` release.

**Comment by yesamer** [comment] 2022-09-14 15:08
@MBoegers 0.23.0 version has been released. Can you please check and eventually close this issue? Thx!

**Comment by ederign** [comment] 2022-09-15 19:13
@MBoegers feel free to reopen if the issue is not fixed!

**Closed as completed by ederign** 2022-09-15 19:13 UTC

**Comment by MBoegers** [comment] 2022-09-23 12:09
Hi, sorry for not responding here, whole was family was _attacked_ by flue. 
I can verify that the button is enabled at every time and the dialog provides expected Java classes, at least for KIE 8 ;)
Thanks for the fix!
