### ISSUE TITLE
Kogito Bundle vscode extension scesim file can not parse dmn file: dmn file is invalid or not presented

### ISSUE THREAD

**Issue by raphael-red** [apache/incubator-kie-tools#884] opened 2022-03-09 08:23 UTC
The issue case is:

When I create a new dmn file with the extension and then create a test scenario file, after select the dmn file and click 'create', the error poped up saying 'dmn file is invalid or not presented'.

So after some work-out I find the first line which is "xml 1.0 version" line cause the case,  so if I delete the first line of the dmn file it works fine.

The extension version is v0.17.0

**Comment by yesamer** [comment] 2022-03-09 08:44
Hi @raphael-red, thank you for reporting this issue. Which is your OS?

**Comment by raphael-red** [comment] 2022-03-09 08:50
> Hi @raphael-red, thank you for reporting this issue. Which is your OS?

My OS is lastest updated Kubuntu 20.04 (amd64)

**Comment by jomarko** [comment] 2022-03-09 15:59
@yesamer @raphael-red hello, here is a quality engineer of DMN eidotr. unfortuantely. I am not able to reproduce the issue.
Using VS Code extension 0.17.0 I was able to:
- Create a new dmn file. In my case containing just InputData node -> Decision node.
- Create a scesim file for the previously created dmn file.

I did this in one of `kogito-examples` project. And even when I run `mvn clean verify`, the newly created scesim passed.

**Comment by raphael-red** [comment] 2022-03-10 01:10
> @yesamer @raphael-red hello, here is a quality engineer of DMN eidotr. unfortuantely. I am not able to reproduce the issue. Using VS Code extension 0.17.0 I was able to:
> 
>     * Create a new dmn file. In my case containing just InputData node -> Decision node.
> 
>     * Create a scesim file for the previously created dmn file.
> 
> 
> I did this in one of `kogito-examples` project. And even when I run `mvn clean verify`, the newly created scesim passed.

Thank you for your effort, it is really weird, I will just delete the line manually for now.

**Comment by jomarko** [comment] 2022-03-10 05:53
@raphael-red would it be possible to share both dmn files?
- created by tooling (that you can not create test scenario for)
- adapted manually by you (that you can  create test scenario for)
?

**Comment by raphael-red** [comment] 2022-03-10 06:37
> @raphael-red would it be possible to share both dmn files?
> 
>     * created by tooling (that you can not create test scenario for)
> 
>     * adapted manually by you (that you can  create test scenario for)
>       ?

I am new to kogito and I just followed the official site doc guiding examples. The only thing I change is deleting the first line `<?xml version="1.0" encoding="UTF-8"?>` create by tooling. So the only difference between the two files is the first line `<?xml version="1.0" encoding="UTF-8"?>`

so the two files will be:
created by tooling (that you can not create test scenario for)
`<?xml version="1.0" encoding="UTF-8"?>
<dmn:definitions xmlns:dmn="http://www.omg.org/spec/DMN/20180521/MODEL/" xmlns="https://kiegroup.org/dmn/_38315640-77B7-464E-9111-1EC1B2999D24" xmlns:feel="http://www.omg.org/spec/DMN/20180521/FEEL/" xmlns:kie="http://www.drools.org/kie/dmn/1.2" xmlns:dmndi="http://www.omg.org/spec/DMN/20180521/DMNDI/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="_B76070BE-FE57-4466-8531-45236D4A4D1A" name="PersonDecisions" typeLanguage="http://www.omg.org/spec/DMN/20180521/FEEL/" namespace="https://kiegroup.org/dmn/_38315640-77B7-464E-9111-1EC1B2999D24">
  <dmn:extensionElements/>
  <dmn:itemDefinition id="_EAA2C173-649D-4C8F-BC3F-1C906F9C2B45" name="tPerson" isCollection="false">
    <dmn:itemComponent id="_2A171125-7520-4F5A-8F2D-587423A2E7ED" name="Adult" isCollection="false">
      <dmn:typeRef>boolean</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_98415359-07E2-4984-B486-C2DDCFEFB565" name="Name" isCollection="false">
      <dmn:typeRef>string</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_9C9396C0-BCB0-4AA7-A0BC-B7BB5019884C" name="Age" isCollection="false">
      <dmn:typeRef>number</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:inputData id="_645B6116-CE35-47A6-AD26-EA07BCB50551" name="Person">
    <dmn:extensionElements/>
    <dmn:variable id="_102AE8EB-1307-48C6-AD57-6674B8CDBEA5" name="Person" typeRef="tPerson"/>
  </dmn:inputData>
  <dmn:decision id="_5C5A7941-A330-46BE-B18A-107CDEB483C6" name="isAdult">
    <dmn:extensionElements/>
    <dmn:variable id="_4BCC422F-C468-4173-9AF2-03DFC0EBF64F" name="isAdult" typeRef="boolean"/>
    <dmn:informationRequirement id="_E3FF87EE-F6FD-4B62-BEEE-524C39994197">
      <dmn:requiredInput href="#_645B6116-CE35-47A6-AD26-EA07BCB50551"/>
    </dmn:informationRequirement>
    <dmn:decisionTable id="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E" hitPolicy="UNIQUE" preferredOrientation="Rule-as-Row">
      <dmn:input id="_A524ECE1-4A27-406C-9011-A75309BE0CE8">
        <dmn:inputExpression id="_4E21B63F-B399-409D-92DD-E0545C02BD3C" typeRef="number">
          <dmn:text>Person.Age</dmn:text>
        </dmn:inputExpression>
      </dmn:input>
      <dmn:output id="_C1569E4F-B697-483D-A14C-0563B061DBC2"/>
      <dmn:annotation name="annotation-1"/>
      <dmn:rule id="_76851CF1-340B-4E3C-B932-DE5B2FEB63AF">
        <dmn:inputEntry id="_C9ECFF4A-FE52-4C74-BD27-3862B0F5F968">
          <dmn:text>&gt; 18</dmn:text>
        </dmn:inputEntry>
        <dmn:outputEntry id="_AC875711-CE3C-4C0F-A25D-D771C3273BD6">
          <dmn:text>true</dmn:text>
        </dmn:outputEntry>
        <dmn:annotationEntry>
          <dmn:text/>
        </dmn:annotationEntry>
      </dmn:rule>
      <dmn:rule id="_CF5D76E0-4579-41C3-AEED-900C5DB079F9">
        <dmn:inputEntry id="_BC109749-ACBA-4D4E-A38D-755AFE5DE623">
          <dmn:text>&lt;= 18</dmn:text>
        </dmn:inputEntry>
        <dmn:outputEntry id="_8CD0634E-E25B-4606-A058-CD729325CB12">
          <dmn:text>false
</dmn:text>
        </dmn:outputEntry>
        <dmn:annotationEntry>
          <dmn:text/>
        </dmn:annotationEntry>
      </dmn:rule>
    </dmn:decisionTable>
  </dmn:decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_4EC7BB6B-5E5D-457E-BA9F-98E4DAED69BB" name="DRG">
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E"/>
        </kie:ComponentsWidthsExtension>
      </di:extension>
      <dmndi:DMNShape id="dmnshape-drg-_645B6116-CE35-47A6-AD26-EA07BCB50551" dmnElementRef="_645B6116-CE35-47A6-AD26-EA07BCB50551" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="204" y="141" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
      <dmndi:DMNShape id="dmnshape-drg-_5C5A7941-A330-46BE-B18A-107CDEB483C6" dmnElementRef="_5C5A7941-A330-46BE-B18A-107CDEB483C6" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="457" y="141" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
      <dmndi:DMNEdge id="dmnedge-drg-_E3FF87EE-F6FD-4B62-BEEE-524C39994197" dmnElementRef="_E3FF87EE-F6FD-4B62-BEEE-524C39994197">
        <di:waypoint x="254" y="166"/>
        <di:waypoint x="457" y="166"/>
      </dmndi:DMNEdge>
    </dmndi:DMNDiagram>
    <dmndi:DMNDiagram id="_B8AF2672-32A1-4B3E-982F-D41023B9E80A" name="new-diagram">
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E"/>
        </kie:ComponentsWidthsExtension>
      </di:extension>
      <dmndi:DMNShape id="dmnshape-new-diagram-_5C5A7941-A330-46BE-B18A-107CDEB483C6" dmnElementRef="_5C5A7941-A330-46BE-B18A-107CDEB483C6" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="457" y="142" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</dmn:definitions>`

 adapted manually by you (that you can  create test scenario for):
`<dmn:definitions xmlns:dmn="http://www.omg.org/spec/DMN/20180521/MODEL/" xmlns="https://kiegroup.org/dmn/_38315640-77B7-464E-9111-1EC1B2999D24" xmlns:feel="http://www.omg.org/spec/DMN/20180521/FEEL/" xmlns:kie="http://www.drools.org/kie/dmn/1.2" xmlns:dmndi="http://www.omg.org/spec/DMN/20180521/DMNDI/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="_B76070BE-FE57-4466-8531-45236D4A4D1A" name="PersonDecisions" typeLanguage="http://www.omg.org/spec/DMN/20180521/FEEL/" namespace="https://kiegroup.org/dmn/_38315640-77B7-464E-9111-1EC1B2999D24">
  <dmn:extensionElements/>
  <dmn:itemDefinition id="_EAA2C173-649D-4C8F-BC3F-1C906F9C2B45" name="tPerson" isCollection="false">
    <dmn:itemComponent id="_2A171125-7520-4F5A-8F2D-587423A2E7ED" name="Adult" isCollection="false">
      <dmn:typeRef>boolean</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_98415359-07E2-4984-B486-C2DDCFEFB565" name="Name" isCollection="false">
      <dmn:typeRef>string</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_9C9396C0-BCB0-4AA7-A0BC-B7BB5019884C" name="Age" isCollection="false">
      <dmn:typeRef>number</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:inputData id="_645B6116-CE35-47A6-AD26-EA07BCB50551" name="Person">
    <dmn:extensionElements/>
    <dmn:variable id="_102AE8EB-1307-48C6-AD57-6674B8CDBEA5" name="Person" typeRef="tPerson"/>
  </dmn:inputData>
  <dmn:decision id="_5C5A7941-A330-46BE-B18A-107CDEB483C6" name="isAdult">
    <dmn:extensionElements/>
    <dmn:variable id="_4BCC422F-C468-4173-9AF2-03DFC0EBF64F" name="isAdult" typeRef="boolean"/>
    <dmn:informationRequirement id="_E3FF87EE-F6FD-4B62-BEEE-524C39994197">
      <dmn:requiredInput href="#_645B6116-CE35-47A6-AD26-EA07BCB50551"/>
    </dmn:informationRequirement>
    <dmn:decisionTable id="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E" hitPolicy="UNIQUE" preferredOrientation="Rule-as-Row">
      <dmn:input id="_A524ECE1-4A27-406C-9011-A75309BE0CE8">
        <dmn:inputExpression id="_4E21B63F-B399-409D-92DD-E0545C02BD3C" typeRef="number">
          <dmn:text>Person.Age</dmn:text>
        </dmn:inputExpression>
      </dmn:input>
      <dmn:output id="_C1569E4F-B697-483D-A14C-0563B061DBC2"/>
      <dmn:annotation name="annotation-1"/>
      <dmn:rule id="_76851CF1-340B-4E3C-B932-DE5B2FEB63AF">
        <dmn:inputEntry id="_C9ECFF4A-FE52-4C74-BD27-3862B0F5F968">
          <dmn:text>&gt; 18</dmn:text>
        </dmn:inputEntry>
        <dmn:outputEntry id="_AC875711-CE3C-4C0F-A25D-D771C3273BD6">
          <dmn:text>true</dmn:text>
        </dmn:outputEntry>
        <dmn:annotationEntry>
          <dmn:text/>
        </dmn:annotationEntry>
      </dmn:rule>
      <dmn:rule id="_CF5D76E0-4579-41C3-AEED-900C5DB079F9">
        <dmn:inputEntry id="_BC109749-ACBA-4D4E-A38D-755AFE5DE623">
          <dmn:text>&lt;= 18</dmn:text>
        </dmn:inputEntry>
        <dmn:outputEntry id="_8CD0634E-E25B-4606-A058-CD729325CB12">
          <dmn:text>false
</dmn:text>
        </dmn:outputEntry>
        <dmn:annotationEntry>
          <dmn:text/>
        </dmn:annotationEntry>
      </dmn:rule>
    </dmn:decisionTable>
  </dmn:decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_4EC7BB6B-5E5D-457E-BA9F-98E4DAED69BB" name="DRG">
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E"/>
        </kie:ComponentsWidthsExtension>
      </di:extension>
      <dmndi:DMNShape id="dmnshape-drg-_645B6116-CE35-47A6-AD26-EA07BCB50551" dmnElementRef="_645B6116-CE35-47A6-AD26-EA07BCB50551" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="204" y="141" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
      <dmndi:DMNShape id="dmnshape-drg-_5C5A7941-A330-46BE-B18A-107CDEB483C6" dmnElementRef="_5C5A7941-A330-46BE-B18A-107CDEB483C6" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="457" y="141" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
      <dmndi:DMNEdge id="dmnedge-drg-_E3FF87EE-F6FD-4B62-BEEE-524C39994197" dmnElementRef="_E3FF87EE-F6FD-4B62-BEEE-524C39994197">
        <di:waypoint x="254" y="166"/>
        <di:waypoint x="457" y="166"/>
      </dmndi:DMNEdge>
    </dmndi:DMNDiagram>
    <dmndi:DMNDiagram id="_B8AF2672-32A1-4B3E-982F-D41023B9E80A" name="new-diagram">
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_27794F3F-B4D8-4F52-AB2D-8BAA4972C71E"/>
        </kie:ComponentsWidthsExtension>
      </di:extension>
      <dmndi:DMNShape id="dmnshape-new-diagram-_5C5A7941-A330-46BE-B18A-107CDEB483C6" dmnElementRef="_5C5A7941-A330-46BE-B18A-107CDEB483C6" isCollapsed="false">
        <dmndi:DMNStyle>
          <dmndi:FillColor red="255" green="255" blue="255"/>
          <dmndi:StrokeColor red="0" green="0" blue="0"/>
          <dmndi:FontColor red="0" green="0" blue="0"/>
        </dmndi:DMNStyle>
        <dc:Bounds x="457" y="142" width="100" height="50"/>
        <dmndi:DMNLabel/>
      </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</dmn:definitions>`

**Comment by jomarko** [comment] 2022-03-10 07:27
Hmm sorry, I tried also your file including "version" prolog. and created scesim without an issue.

![Screenshot from 2022-03-10 08-21-32](https://user-images.githubusercontent.com/8044780/157609740-2ccf3707-2718-4309-b83e-b6f06d0c682f.png)


Could you please clarify what bundle you have installed?
- DMN Editor (redhat.vscode-extension-dmn-editor)
- BPMN Editor (redhat.vscode-extension-bpmn-editor)
- Red Hat Business Automation Bundle (redhat.vscode-extension-red-hat-business-automation-bundle)
- Kogito Bundle (kie-group.vscode-extension-kogito-bundle)

**Comment by raphael-red** [comment] 2022-03-10 08:05
> Hmm sorry, I tried also your file including "version" prolog. and created scesim without an issue.
> 
> ![Screenshot from 2022-03-10 08-21-32](https://user-images.githubusercontent.com/8044780/157609740-2ccf3707-2718-4309-b83e-b6f06d0c682f.png)
> 
> Could you please clarify what bundle you have installed?
> 
>     * DMN Editor (redhat.vscode-extension-dmn-editor)
> 
>     * BPMN Editor (redhat.vscode-extension-bpmn-editor)
> 
>     * Red Hat Business Automation Bundle (redhat.vscode-extension-red-hat-business-automation-bundle)
> 
>     * Kogito Bundle (kie-group.vscode-extension-kogito-bundle)

Hmm I tried it again, it worked well too. I am sorry for wasting your time. Though I was pretty sure I deleted the line to make it work but now the fact shows the other case. I feel embarrassed. Now I doubt that I edited file in the intellij idea too, may be the vscode is initializing so the classpath hasn't loaded yet. Which I am not sure.

Though I am sure that the "version" prolog in the scesim file will cause the test fail: `[ERROR] testscenario.KogitoScenarioJunitActivatorTest  Time elapsed: 0.012 s  <<< ERROR!
org.drools.scenariosimulation.backend.runner.ScenarioException: Issue on parsing file: /home/nd/Learning/sample-kogito-2/target/test-classes/PersonDecisionTest.scesim`. I delete the "version" prolog in the scesim file in the target directory and rerun "mvn test" which will pass the test. Anyway it's another issue don't know if it's related to this repo.

**Comment by yesamer** [comment] 2022-03-10 08:20
> Though I am sure that the "version" prolog in the scesim file will cause the test fail: [ERROR] testscenario.KogitoScenarioJunitActivatorTest Time elapsed: 0.012 s <<< ERROR! org.drools.scenariosimulation.backend.runner.ScenarioException: Issue on parsing file: /home/nd/Learning/sample-kogito-2/target/test-classes/PersonDecisionTest.scesim. I delete the "version" prolog in the scesim file in the target directory and rerun "mvn test" which will pass the test. Anyway it's another issue don't know if it's related to this repo.

@raphael-red Yes, that is a different issue we already aware of, It should be fixed with kogito runtime 1.18.0 version. Can you please update the version in your POM and try again?

**Comment by yesamer** [comment] 2022-03-14 09:24
@raphael-red  Can you please confirm updating to `kogito-runtime` version 1.18.0 solved the issue?

**Comment by ederign** [comment] 2022-04-20 18:48
@raphael-red I'm closing this issue due to inactivity. If you still face this bug with the most recent version, feel free to reopen it.

**Closed as completed by ederign** 2022-04-20 18:48 UTC
